- id: terraform-conda
  name: terraform-conda
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: hooks/terraform_fmt.sh
  language: conda
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$
